### ISSUE TITLE
Segfault because of null-pointer when Connect fails

### ISSUE THREAD

**Issue by hafkensite** [linxGnu/mssqlx#1]
I was hoping to make our application more resilient against db outages, but when one of the dsns is down during initial connect the first query will trigger a segfault:
```
github.com/linxGnu/mssqlx._query.func1(0x6b2da8, 0xc000124200, 0xc000140060, 0xc0000fd858)
        /home/jasper/go/pkg/mod/github.com/linx!gnu/mssqlx@v1.0.6/mssqlx.go:682 +0x3b
github.com/linxGnu/mssqlx.retryBackoff(0xc0000341e0, 0x48, 0xc0000fd8c0, 0x0, 0x16, 0x2, 0x16)
        /home/jasper/go/pkg/mod/github.com/linx!gnu/mssqlx@v1.0.6/mssqlx.go:521 +0x65
github.com/linxGnu/mssqlx._query(0x9c5600, 0xc0000ae058, 0xc000106680, 0xc0000341e0, 0x48, 0x0, 0x0, 0x0, 0x48, 0xc000176280, ...)
        /home/jasper/go/pkg/mod/github.com/linx!gnu/mssqlx@v1.0.6/mssqlx.go:681 +0x14a
github.com/linxGnu/mssqlx.(*DBs).Query(...)
        /home/jasper/go/pkg/mod/github.com/linx!gnu/mssqlx@v1.0.6/mssqlx.go:702
```
I think it can be fixed by using `sqlx.Open` in `ConnectMasterSlaves` instead of `sqlx.Connect` here: https://github.com/linxGnu/mssqlx/blob/28aead0ae88b56947a357c326ffde0ac19ca4bf8/mssqlx.go#L1488 (and a few lines lower for the slaves).

**Comment by linxGnu** [comment]
@hafkensite Thank you very much for pointing out. I think it's reasonable to use sqlx.Open instead. Could you please make a PR.
:+1:

**Comment by linxGnu** [comment]
I will close the issue. Thank you very much @hafkensite
