### ISSUE TITLE
QueryRow implementation is incorrect

### ISSUE THREAD

**Issue by Bhrn** [linxGnu/mssqlx#11]
https://github.com/linxGnu/mssqlx/blob/7295fe3e97e87455142642288cca3c44c7f88189/mssqlx.go#L779

As per commenting on the function: "Errors are deferred until Row's Scan method is called."

This implementation mistake has been made with all variations of the "QueryRow" functions.

**Comment by linxGnu** [comment]
@Bhrn I think the mistake here is the comment. Mssqlx performs health checking for fail fast. Error is returned when no node available for query.

I would like to update the comments if you think it's ambiguous. Please let me know your thought, thank you for using mssqlx.

**Comment by Bhrn** [comment]
@linxGnu I understand the interest in fail fast however if you look at the base library that your code is implemented on top of (github.com/jmoiron/sqlx) you will notice that all QueryRow functions defer the error to the Row's Scan method.  While this does defeat a fast fail, it allows me to make statements like this (using the go SQL implementation as an example but this should also apply to the mssqlx implementations)
`var age int64
err := db.QueryRowContext(ctx, "SELECT age FROM users WHERE name = $1", name).Scan(&age)`
(Copied from https://github.com/golang/go/wiki/SQLInterface)
This allows for a clean entry in the code which automatically handles the closing of the Row and a single record to be retrieved.  It makes sense that the QueryRow implementations follow the same flow as the base libraries, no?

**Comment by linxGnu** [comment]
@Bhrn 
Yeah, due to health check, `mssqlx` provides another set of api (compare to go standard). I also agree that you could not perform method chaining like `db.QueryRowContext(ctx, "SELECT age FROM users WHERE name = $1", name).Scan(&age)` right now.

I could update the API to return `sql.Row`:
- Row will belong a healthy node if possible. Otherwise, will belong to a random failed node.

However, I don't think it's a good way at all. Why I should provide row pointing to a node that I know it's failing. By the way, I think it's matter of choice. I am 50-50.

**Comment by Bhrn** [comment]
I confess that the first time I read the way that that was implemented in go I was surprised that the error would be returned by the Row object instead of directly but when considering that this allowed for chaining the Scan, I understood why it was done this way.  

I see why you would feel uncomfortable returning a Row object if it belonged to a random failed node.

The only complication I can see is that the current implementation will return some types of errors directly from the call to the QueryRow functions and will defer some other types of errors until the Row.Scan call.  This leaves an inconsistency in how errors are treated for QueryRow type calls in the mssqlx implementation.  This is unclear from the comments.

I prefer that the implementation allows for the chaining.  If you choose otherwise, I'd recommend that the comments be updated to indicate that some of the errors are deferred until Row's Scan method is called and errors for when no node is available for the query are not deferred.

**Comment by linxGnu** [comment]
@Bhrn I think I would follow your suggestion. As what I want is serving user's need.

PTAL: https://github.com/linxGnu/mssqlx/pull/12

**Comment by linxGnu** [comment]
I have just released v1.1.3 which contains the fix. PTAL: https://github.com/linxGnu/mssqlx/releases/tag/v1.1.3

Please feel free to tell me if you have another concern. Thank you very much for using mssqlx as well as great suggestion @Bhrn
